### ISSUE TITLE
Solution?

### ISSUE THREAD

**Issue by gonzoguajardo** [mickaeltr/spring-data-jpa-bug-with-native-query-uuid-projection#1]
Did you find a solution for this by chance?

**Comment by gonzoguajardo** [comment]
Casting seems to have helped. `@Query(value = "SELECT cast(p.id as varchar) FROM person p WHERE p.id = :#{#id}", nativeQuery = true)`

**Comment by mickaeltr** [comment]
More details can be found here: https://jira.spring.io/browse/DATAJPA-1480
